version: 2

anchors:
  build: &build
    working_directory: ~/build
    steps:
      - checkout:
          path: ~/project

      - run: cmake ~/project -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: ninja -v -j 3

jobs:
  build:
    docker:
      - image: kiks/build-env
    <<: *build

workflows:
  version: 2
  build:
    jobs:
      - build
