name: Build
on: [push, pull_request]

jobs:
  buid:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install protobuf
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler
      - name: Install protobuf
        if: runner.os == 'macOS'
        run: brew install protobuf

      - run: cmake -S . -B build
      - run: cmake --build build -v
